### ISSUE TITLE
Ropro plus server filters not working

### ISSUE THREAD

**Issue by robux1236543** [Stefanuk12/RoProPatcher#33] opened 2023-07-12 09:48 UTC
When I try to use any ropro plus server filters, (Best connection, server region, etc) it doesn't show the servers I chose. For example, if I select my server region to be in Mumbai India then click on the dot for that region, it will not show any servers. Here are some screenshots. 
![Screenshot (92)](https://github.com/Stefanuk12/RoProPatcher/assets/139339911/e19c64e2-9151-41b3-b6e4-1ae0c748a5d6)
![Screenshot (93)](https://github.com/Stefanuk12/RoProPatcher/assets/139339911/072e4d96-2b8f-4c01-92d6-929687ee4f5c)
![Screenshot (94)](https://github.com/Stefanuk12/RoProPatcher/assets/139339911/71ce7531-293c-48b7-aa39-79234ce4733e)

**Comment by Stefanuk12** [comment] 2023-07-12 11:32
Duplicate of #31

**Closed** 2023-07-12 11:32 UTC
