### ISSUE TITLE
new update or smth

### ISSUE THREAD

**Issue by Night-boxx** [Stefanuk12/RoProPatcher#64] opened 2024-05-14 19:00 UTC
**Describe the bug**
the devs prbl fixed the patcher version and it doesnt show up and doesnt connect to the network + the videos dont work and the text idk

**Expected behavior**
it doesnt load the new extension

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [PC]
 - Browser [Opera GX]
 - v1.3

**Comment by Stefanuk12** [comment] 2024-05-14 19:02
Duplicate of #62.

**Closed as completed** 2024-05-14 19:03 UTC
