### ISSUE TITLE
server filters dont work

### ISSUE THREAD

**Issue by hahjonachirsar** [Stefanuk12/RoProPatcher#63] opened 2024-05-09 08:39 UTC
is there a cause and a possible fix? i cant use the server region option and pressing best connection leads to nothing

**Comment by BZQ1** [comment] 2024-05-09 09:19
the token expired or they patched it

**Comment by Stefanuk12** [comment] 2024-05-09 13:56
Duplicate of #62

**Closed by Stefanuk12** 2024-05-09 13:56 UTC
